# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/sqlalchemyorg/zimports
    rev: 0.2.2
    hooks:
    -   id: zimports
        types: [file]
        files: \.(py|pyi)$

-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: [file]
        files: \.(py|pyi)$


